target'FMClient3.0' do

platform :ios,'7.0'
pod 'AFNetworking','~>3.0.1'
pod 'FMDB','2.6.2'
pod 'LKDBHelper', '~> 2.2.1'
pod 'SDWebImage', '~> 3.7.6'
pod 'SVProgressHUD', '~> 2.0.3'
pod 'ZBarSDK', '~> 1.3.1'

end
